<a href="https://colab.research.google.com/github/bwsi-hadr/01-Intro-to-python/blob/master/01_Intro_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to python (a review)
In this lesson, we'll review basic python and programming concepts, as well as go over the fundamentals of how to use some common python packages, such as:
- numpy
- pandas
- matplotlib

## Importing packages
Packages are collections of pre-written code made available for reuse. In the previous lesson, we installed some necessary packages using the `pip` python package manager. Packages are convenient because they save you from having to implement every feature and function on your own. The widely-used packages also provide a standard, common set of tools for others to develop with --- allowing interoperability between programs.

There are a few different ways to import  package in python:

The simplest is just to `import {packagename}`. For this lesson, we'll use `numpy` as the example package
```
import numpy
```
The functions, classes, and variables of the `numpy` package can then be accessed using "dot" notation: for example, the numpy array class can be accessed with `numpy.array`

---
A variant of this is to use `import {packagename} as {shortname}`, as in:
```
import numpy as np
```
This reduces the number of characters needed to type, and can be convenient if the package name is long, or you need to use many things from the same package. Accessing the numpy array class, for example, can be done with ```np.array```

---

If you only need a subset of items from a package, for example, a single class, function, or a submodule (subpackage of the main package), you can use the syntax ``` from {packagename} import {element}```, as in:
```
from numpy import array
```
This allows you to use the `array` class directly, without importing the rest of the numpy package, and without needing to use the package prefix dot notation.
For example, if you use this import method, then writing
```
test_array = array([0])
```
would be equivalent to writing
```
test_array = numpy.array([0])
test_array = np.array([0])
```
using the previous import styles, respectively.

In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot


## Documentation

Packages contain functions, classes, and variables which may be helpful. Crucial to the usability of a package is the documentation (or API reference), which (should) list all of the contents of the package, and how to use them.

To get the built-in help about a function or class, use the `help()` command

Documentation for most common packages are also usually available online. For example, the documentation for [numpy can be found here](https://docs.scipy.org/doc/numpy/reference/)

In [15]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

### Commenting code
In order for your code to be readable to others (or your future self), you should provide comments on your code to explain what you are doing. The comment character in python is `#`, and any text following a `#` symbol will not be interpreted as code by python.

In [18]:
array_of_zeros = np.zeros([3,3]) # this creates a 3x3 array full of zeros
print(array_of_zeros) # the print() function displays the value of the variable on screen

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
